Undo Last Commit + Bug Fix Of Speed()
Rather Than Speed() I Wrote Rot() , So It Throws A Error

AttributeError: 'Motor' object has no attribute 'Rot'

Fixed By Using The Actual Function